name: C++ Tests

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake g++ make git libgtest-dev
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp lib/*.a /usr/lib
        cd ~
    
    - name: get code
      uses: actions/checkout@v4


    - name: build and test
      run: make test-debug